apiVersion: apps/v1
kind: Deployment
metadata:
  namespace: rtb
  name: productpage-service-app
  labels:
    app: productpage-service-app
spec:
  replicas: 1
  selector:
    matchLabels:
      app : productpage-service-app
  template:
    metadata:
      labels:
        app: productpage-service-app
    spec:
      containers:
        - name: productpage-service-app
          image: mamoonroshangar/productpage-service:latest
          imagePullPolicy: Always
          ports:
            - containerPort: 9004
          env: # Setting Environmental Variables
            - name: DB_HOST   # Setting Database host address from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: host

            - name: DB_NAME  # Setting Database name from configMap
              valueFrom:
                configMapKeyRef:
                  name: db-config
                  key: dbName

            - name: DB_USERNAME  # Setting Database username from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: username

            - name: DB_PASSWORD # Setting Database password from Secret
              valueFrom:
                secretKeyRef:
                  name: mysql-secrets
                  key: password

---

kind: Service
apiVersion: v1
metadata:
  namespace: rtb
  name: productpage-service-svc
spec:
  selector:
    app: productpage-service-app
  ports:
    - port: 80
      targetPort: 9004